title: bigw
description: > # this means to ignore newlines until "baseurl:"
  高高山顶立，深深海底行。
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: bigw # add your name
author-img: bigw.jpg # add your photo
about-author: 独立个体。
  这里用来记录工作学习上的一些思考。
  希望能通过这种方式，能记录下当时刚接触到它时的那种快乐。
social-twitter: none # add your Twitter handle
social-facebook: none # add your Facebook handle
social-github: hopestar # add your Github handle
social-linkedin: none # add your Linkedin handle
social-email: h6166786@163.com # add your Email address

# Disqus
discus-identifier: bigw # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 12
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
